### PR TITLE
Resolves #234

### LINKED ISSUE #234: Incorrect position of Drag Handle
I have novel inside Dialog window (to be precise Shadcn Dialog) and Draggable handle has incorrect position when I hover something. It is below the content, which means I can't reach it by any means as it disappears before I can click it to move the box.

image

Here it is live:
https://coursition.com/demo/edit - just add the TextEditor component and open the editor. :)

## Expected outcome
Drag Handle is correctly positioned

## Current outcome
Drag Handle can't be reached by any means

### PR DESCRIPTION
**Pull request by haydenbleasel**
Implement's a simpler version of @BleedingDev's fix. Confirmed it works without dialog:

CleanShot 2024-03-15 at 22 46 28@2x

and with dialog:

CleanShot 2024-03-15 at 22 46 15@2x

### CODE REVIEW

**Comment by haydenbleasel** [comment]
Sorry about the excess commits, started from the original fix and worked backwards to effectively rebase it.

File: packages/headless/src/extensions/drag-and-drop.tsx [hunk 1]
```diff
@@ -12,6 +12,17 @@ export interface DragHandleOptions {
 }
 function absoluteRect(node: Element) {
   const data = node.getBoundingClientRect();
+  const modal = node.closest('[role="dialog"]');
```
Comment (andrewdoro) [inline packages/headless/src/extensions/drag-and-drop.tsx:15]: should we also add something about this to the docs, I don't know if all people use this attr for their dialog`[role="dialog"]`. Wyt?

**Comment by haydenbleasel** [comment]
@andrewdoro Updated the docs to note dialog usage.

**Review by andrewdoro — APPROVED** [review]
